language: groovy
branches:
  only:
    - master
    - developer

before_script:
 - chmod +x grailsw
 - chmod +x travis-build.sh

script: ./travis-build.sh

notifications:
  email:
    - marianoekfuri@gmail.com
    - mmicciullo@gmail.com
