sudo: false
language: groovy
branches:
  only:
    - master
    - developer
    - /^hotfix-.*$/
    - /^release-.*$/
    - migrate-grails3.x


before_script:
 - chmod +x gradlew
 - chmod +x travis-build.sh

script: ./travis-build.sh

notifications:
  slack:
    secure: CH8XkPAueZBVF60DaFRAM6ajNiG3mRCBZFlRbNd5Ya1ivPUSKYJQp1jJVoSQizd4EabEbK1/1+dDwBm+OiEoNN3FAzkleC8DZNSh/EjmQT2RArLZrv41dx2RlKkMyB0oF16mN6ivDGQofqDqBNDcWOZGpgnewGMgHMWtEluAOrA=
